app/urls.py
from django.contrib import admin
from django.urls import path, include

from pharmapp.app import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('store/', include('goods.urls', namespace='store')),
    path('user/', include('users.urls', namespace='user')),
    path('experiment/', include('experiments.urls', namespace='experiment')),
    path('works/', include('works.urls', namespace='works')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

experiments/urls.py
from django.urls import path

from pharmapp.experiments import views

app_name = 'experiments'

urlpatterns = [
    path('experiment_add/', views.experiment_add, name='experiment_add'),
    path('experiment_change/', views.experiment_change, name='experiment_change'),
    path('experiment_remove/', views.experiment_remove, name='experiment_remove'),
]

experiments/models.py
from django.db import models
from pharmapp.goods.models import Items
from pharmapp.users.models import User


class ExperimentQueryset(models.QuerySet):

    def total_quantity(self):
        if self:
            return sum(experiment.quantity for experiment in self)
        return 0


class Experiment(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    item = models.ForeignKey(to=Items, on_delete=models.CASCADE, verbose_name='Предмет')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    # date = models.DateTimeField(verbose_name='Дата эксперимента')
    approved = models.BooleanField(default=False, verbose_name='Одобрено')
    session_key = models.CharField(max_length=32, null=True, blank=True)

    class Meta:
        db_table = 'experiment'
        verbose_name = 'Эксперимент'
        verbose_name_plural = 'Эксперименты'

    objects = ExperimentQueryset().as_manager()

    def __str__(self):
        if self.user:
            return f" Эксперимент {self.user.username} | Предмет {self.item.name} | Количество {self.quantity}"
        return f" Эксперимент незарегистрированного пользователя | Предмет {self.item.name} | Количество {self.quantity}"

    def experiment_date(self):
        return f" Дата: {self.created_timestamp}"

experiments/views.py
from pharmapp.goods.models import Items
from pharmapp.experiments.models import Experiment
from django.http import JsonResponse
from django.template.loader import render_to_string
from pharmapp.experiments.utilts import get_user_experiments


def experiment_add(request):

    item_id = request.POST.get("item_id")

    item = Items.objects.get(id=item_id)

    if request.user.is_authenticated:
        experiments = Experiment.objects.filter(user=request.user, item=item)

        if experiments.exists():
            experiment = experiments.first()
            if experiment:
                experiment.quantity += 1
                experiment.save()
        else:
            Experiment.objects.create(user=request.user, item=item, quantity=1)

    else:
        experiments: Experiment.objects.filter(
            session_key=request.session_key, item=item
        )
        if experiments.exists():
            experiment: experiments.first()
            if experiment:
                experiment.quantity += 1
                experiment.save()
        else:
            Experiment.objects.create(session_key=request.session.session_key, item=item, quantity=1)

    user_experiments = get_user_experiments(request)

    experiment_items_html = render_to_string(
        "experiments/includes/included_experiment.html", {"experiments": user_experiments}, request=request,
    )

    response_data = {
        'message': 'Предмет добавлен для эксперимента',
        'experiment_items_html': experiment_items_html,
    }

    return JsonResponse(response_data)


def experiment_change(request):
    experiment_id = request.POST.get("experiment_id")
    quantity = request.POST.get("quantity")

    experiment = Experiment.objects.get(id=experiment_id)

    experiment.quantity = quantity
    experiment.save()

    experiment = get_user_experiments(request)
    experiment_items_html = render_to_string(
        "experiments/includes/included_experiment.html", {"experiments": experiment}, request=request
    )

    response_data = {
        'message': 'Количество изменено',
        'experiment_items_html': experiment_items_html
    }

    return JsonResponse(response_data)


def experiment_remove(request, experiment_id):

    experiment_id = request.POST.get("experiment_id")

    experiment = Experiment.objects.get(id=experiment_id)
    quantity = experiment.quantity
    experiment.delete()

    user_experiment = get_user_experiments(request)
    experiment_items_html = render_to_string(
        "experiments/includes/included_experiment.html", {"experiments": user_experiment}, request=request
    )
    response_data = {
        "message": 'Предмет удалён из эксперимента',
        "experiment_items_html": experiment_items_html,
        "quantity_deleted": quantity,
    }

    return JsonResponse(response_data)

experiments/templates/experiments/includes/included_experiment.html
{% load static %}


<div class="card mb-3 text-bg-light shadow-lg">
    {% for experiment in experiments %}
    <div class="card-header">
        <h5 class="card-title">{{ experiment.item.name }}</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="row text-center">
                <div class="col p-0">
                    <div class="input-group">
            <span class="input-group-btn">
              <button type="button" class="btn btn-dark btn-sm decrement"
                      data-cart-id="{{experiment.id}}"
                      data-experiment-change-url="{% url "experiment:experiment_change" %}">
                {% csrf_token %}
                -</button>
            </span>
                        <input type="text" class="form-control number" value="{{ experiment.quantity }}" readonly>
                        <span class="input-group-btn">
            <button type="button" class="btn btn-dark btn-sm increment"
                    data-experiment-id="{{experiment.id}}"
                    data-experiment-change-url="{% url "experiment:experiment_change" %}">
                            {% csrf_token %}
                            +</button>
            </span>
                    </div>
                </div>
                <div class="col p-0">
                    <p>грамм</p>
                </div>
                <div class="col p-0"><strong>водный раствор</strong></div>
                <div class="col p-0">
                    <a href=" {% url "experiment:experiment_remove"%}" class="remove-from-experiment"
                    data-experiment-id="{{experiment.id}}">
                        {% csrf_token %}
                    <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}" alt="Catalog Icon" width="16" height="16">
                    </a>
                </div>
            </div>
        </li>
    </ul>
    {% endfor %}

</div>
    <div class="card mb-3 shadow-lg">
        <div class="card-footer">
            <p class="float-left">Всего: <strong>{{experiments.total_quantity}}</strong> предметов на дату: </p>
                <h4 class="float-left"><strong>У вас нет запланированных экспериментов </strong></h4>
        </div>
    </div>