app/urls.py
from django.contrib import admin
from django.urls import path, include

from pharmapp.app import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('store/', include('goods.urls', namespace='store')),
    path('user/', include('users.urls', namespace='user')),
    path('experiment/', include('experiments.urls', namespace='experiment')),
    path('works/', include('works.urls', namespace='works')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from pharmapp.users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('users-experiment/', views.users_experiment, name='users_experiment'),
]

works/urls.py
from django.urls import path
from pharmapp.works import views

app_name = 'works'

urlpatterns = [
    path('create-work/', views.create_work, name='create_work')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from pharmapp.users.models import User


# проверка данных на соответсвие, прежде чем отправлять их в бд

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()
    # username = forms.CharField(
    #     label='Имя пользователя',
    #     widget=forms.TextInput(attrs={
    #         "autofocus": True,
    #         'class': 'form-control',
    #         'placeholder': 'Введите ваше имя пользователя'
    #     }
    #     )
    # )
    # password = forms.CharField(
    #     label='Пароль',
    #     widget=forms.PasswordInput(attrs={
    #         "autofocus": "current-password",
    #         'class': 'form-control',
    #         'placeholder': 'Введите ваш пароль'
    #     }
    #     )
    # )


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'image',
        )
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    image = forms.ImageField(required=False)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.urls import reverse

from pharmapp.experiments.models import Experiment
from pharmapp.users.forms import UserLoginForm, UserRegistrationForm, ProfileForm
from django.contrib.auth.decorators import login_required

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                if session_key:
                    Experiment.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get('next, None')
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                if request.POST.get('next', None):
                    return HttpResponseRedirect(request.POST.get('next'))
                return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserLoginForm()
    context = {
        'title': 'Авторизация',
        'form': form
    }

    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Experiment.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, f"{user.username}, Вы успешно зарегистрировались и вошли в аккаукнт")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профиль обновлён")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    context = {
        'title': 'Личный кабинет',
        'form': form
    }
    return render(request, 'users/profile.html', context)

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('main:index'))


def users_experiment(request):
    return render(request, 'users/users_experiment.html')

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block modal_experiment %}
{% include "includes/experiment_button.html" %}
{% endblock %}

{% block content %}
<div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                                    <h2 class="text-center mb-4">Авторизация</h2>
                                    <form action=" {% url "user:login" %} " method="post">
                                    {% csrf_token %}

                                    {% if request.GET.next %}
                                        <input type="hidden" name="next" value={{request.GET.next}}>
                                    {% endif %}

                                    <div class="mb-3">
                                        <label for="username" class="form-label">Имя пользователя</label>
                                        <input type="text" class="form-control"
                                               name="username"
                                               value="{% if form.username.value%}{{ form.username.value }}{% endif %}"
                                               id="username" placeholder="Введите ваше имя пользователя"
                                               required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="password" class="form-label">Пароль</label>
                                        <input type="password" class="form-control" name="password"
                                               id="password" placeholder="Введите ваш пароль"
                                               required>
                                    </div>
                                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                                    </form>
                                    <!--                                    {% for item in form %}-->
                                    <!--                                        <div class="mb-3">-->
                                    <!--                                            <label for="{{ item.id_for_label}}" class="form-label">{{item.label}}</label>-->
                                    <!--                                            {{item}}-->
                                    <!--                                        </div>-->
                                    <!--                                    {% endfor %}-->
                                    <div class="mt-3">
                                        <a href="#">Забыли пароль?</a> | <a href="{% url "user:registration"%}">Создать аккаунт</a>
                                    </div>
                                    <hr>
                                    <div class="text-center">
                                        <p>Или авторизуйтесь через:</p>
                                        <a href="#" class="btn btn-dark">
                                            <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                                            Google
                                        </a>
                                        <a href="#" class="btn btn-dark">
                                            <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                                            Facebook
                                        </a>
                                        <a href="#" class="btn btn-dark">
                                            <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                                            GitHub
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block modal_experiment %}
{% include "includes/experiment_button.html" %}
{% endblock %}

{% block content %}
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                                    <h2 class="text-center mb-4">Регистрация</h2>
                                    <form action=" {% url "user:registration" %} " method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="id_first_name" class="form-label">Имя*</label>
                                                <input type="text" class="form-control" id="id_first_name" value="{% if form.first_name.value%}{{ form.first_name.value }}{% endif %}" name="first_name" placeholder="Введите ваше имя" required>
                                                {% if form.first_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                                <input type="text" class="form-control" id="id_last_name" value="{% if form.last_name.value%}{{ form.last_name.value }}{% endif %}" name="last_name" placeholder="Введите вашу фамилию" required>
                                                {% if form.last_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                                <input type="text" class="form-control" id="id_username" value="{% if form.username.value%}{{ form.username.value }}{% endif %}" name="username" placeholder="Введите ваше имя пользователя" required>
                                                {% if form.username.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_email" class="form-label">Email*</label>
                                                <input type="email" class="form-control" id="id_email" value="{% if form.email.value%}{{ form.email.value }}{% endif %}" name="email" placeholder="Введите ваш email" required>
                                                {% if form.email.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_password1" class="form-label">Пароль*</label>
                                                <input type="password" class="form-control" id="id_password1" value="{% if form.password1.value%}{{ form.password1.value }}{% endif %}" name="password1" placeholder="Введите пароль" required>
                                                {% if form.password1.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                                <input type="password" class="form-control" id="id_password2" value="{% if form.password2.value%}{{ form.password2.value }}{% endif %}" name="password2" placeholder="Подтвердите пароль" required>
                                                {% if form.password2.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                                {% endif %}
                                            </div>
                                        </div>
                                        <button type="submit"
                                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

users/templates/users/users_experiment.html
{% extends "base.html" %}
{% load static %}
{% load experiments_tags %}

{% block content %}
{% user_experiments request as experiments %}
<div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                    <h3 class="text-center mb-4">Эксперимент</h3>
                                    <div class="container" id="experiment-items-container">
                                        <!-- Разметка корзины -->
                                        {% include "experiments/includes/included_experiment.html" %}
                                        <!-- Закончилась разметка корзины , Разметка в шапке пользователя -->
                                    </div>
                                    {% if experiments %}
                                    <a class="btn btn-dark" href="{% url "works:create_work" %}">
                                        Отправить эксперимент на одобрение
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}