app/urls.py
from django.contrib import admin
from django.urls import path, include

from pharmapp.app import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('store/', include('goods.urls', namespace='store')),
    path('user/', include('users.urls', namespace='user')),
    path('experiment/', include('experiments.urls', namespace='experiment')),
    path('works/', include('works.urls', namespace='works')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

experiments/urls.py
from django.urls import path

from pharmapp.experiments import views

app_name = 'experiments'

urlpatterns = [
    path('experiment_add/', views.experiment_add, name='experiment_add'),
    path('experiment_change/', views.experiment_change, name='experiment_change'),
    path('experiment_remove/', views.experiment_remove, name='experiment_remove'),
]

goods/urls.py
from django.urls import path

from pharmapp.goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.store, name='search'),
    path('<slug:category_slug>/', views.store, name='index'),
    path('item/<slug:item_slug>/', views.item, name='item'),
]

main/urls.py
from django.urls import path

from pharmapp.main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

users/urls.py
from django.urls import path

from pharmapp.users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('users-experiment/', views.users_experiment, name='users_experiment'),
]

templates/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}
    {% endblock %}
    <!--    чтоб прилипал к низу страницы-->
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">

    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "user:users_experiment" %}">Эксперимент</a>
                        </li>
                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "user:login"%}">Войти</a>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
<!--                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>-->
                                <li><a class="dropdown-item  text-white" href="{% url "user:profile"%}">Личный кабинет</a>
                                </li>
                                {% if user.is_admin or user.is_staff %}
                                    <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "user:logout"%}">Выйти</a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" action=" {% url "store:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Склад
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                        <li><a class="dropdown-item text-white" href="{% url "store:index" category.slug %}">{{category.name}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->

                {% block modal_experiment %} {% endblock %}
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% include "includes/notifications.html" %}
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}
    {% endblock %}
    <script src="{% static "deps\js\jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

templates/think.html
<!--{% block content %}-->
<!--    <div class="container mt-5">-->
<!--                        <div class="card mb-4 custom-shadow">-->
<!--                            <div class="row">-->
<!--                                &lt;!&ndash; Миниатюры &ndash;&gt;-->
<!--                                <div class="col-md-4">-->
<!--                                    {% if not item.image%}-->
<!--                                    <img hidde="True"-->
<!--                                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">-->

<!--                                    {% else %}-->
<!--                                    <img src="{{ item.image.url }}"-->
<!--                                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">-->
<!--                                    {% endif %}-->

<!--                                </div>-->
<!--                                <div class="col-md-4 ">-->

<!--                                    <div class="crop"><img src="{% static "deps/images/ts.jpg" %}" class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1"></div>-->
<!--                                    <p class="product_id mt-3">ID: {{item.display_id}}</p>-->
<!--                                </div>-->
<!--                                &lt;!&ndash; Увеличить изображение в модальном окне &ndash;&gt;-->
<!--                                <div class="modal fade" id="imageModal1" tabindex="-1"-->
<!--                                    aria-labelledby="imageModal1Label" aria-hidden="true">-->
<!--                                    <div class="modal-dialog modal-lg">-->
<!--                                        <div class="modal-content">-->
<!--                                            <div class="modal-header">-->
<!--                                                <h5 class="modal-title" id="imageModal1Label">{{item.name}}</h5>-->
<!--                                                <button type="button" class="btn-close" data-bs-dismiss="modal"-->
<!--                                                    aria-label="Закрыть"></button>-->
<!--                                            </div>-->
<!--                                            <div class="modal-body">-->
<!--                                                {% if not item.image %}-->
<!--                                                <img hidden="True"-->
<!--                                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">-->
<!--                                                {% else %}-->
<!--                                                <img src="{{ item.image.url }}"-->
<!--                                                    class="img-fluid" alt="Изображение 1">-->
<!--                                                {% endif %}-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->


<!--                            &lt;!&ndash; Описание товара &ndash;&gt;-->
<!--                            <div class="card-body">-->
<!--                                <div class="alert">-->
<!--                                <h5 class="card-title">{{item.name}}</h5>-->
<!--                                <p class="card-text">{{item.description}}</p>-->
<!--                                <p class="card-text">Количество: <strong>{{item.quantity}}</strong></p>-->
<!--                                <h5 class="card-title">Готовность к работе:</h5>-->

<!--                                    <h6>Да</h6>-->
<!--                                <h6>-->
<!--                                    <a href="#" class="btn btn-outline-dark">Параметры проведения процесса:</a>-->
<!--                                    <input type="text" placeholder="Давление, температура">-->
<!--                                    <br>-->
<!--                                    <br>-->
<!--                                    <a href="#" class="btn btn-outline-dark">Дата бронирования оборудования:</a> <input type="date">-->
<!--                                </h6>-->
<!--                                <a href="{% url "experiment:experiment_add"%}" class="btn btn-dark add-to-experiment" data-item-id="{{item.id}}">-->

<!--                                {% csrf_token %}-->
<!--                                Добавить для экспериментов</a>-->
<!--                                </div>-->

<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--{% endblock %}-->

templates/think2.html
{% extends "base.html" %}
{% load static %}

{% block modal_experiment %}
{% include "includes/experiment_button.html" %}
{% endblock %}


{% block content %}
    <div class="container mt-5">
                        <div class="card mb-4 custom-shadow">
                            <div class="row">
                                <!-- Миниатюры -->
                                <div class="col-md-4">
                                    {% if not item.image%}
                                    <img hidde="True"
                                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">

                                    {% else %}
                                    <img src="{{ item.image.url }}"
                                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                                    {% endif %}

                                </div>
                                <div class="col-md-4 ">
                                    <p class="product_id mt-3">ID: {{item.display_id}}</p>
                                </div>
                                <!-- Увеличить изображение в модальном окне -->
                                <div class="modal fade" id="imageModal1" tabindex="-1"
                                    aria-labelledby="imageModal1Label" aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="imageModal1Label">{{item.name}}</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Закрыть"></button>
                                            </div>
                                            <div class="modal-body">
                                                {% if not item.image %}
                                                <img hidden="True"
                                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                                                {% else %}
                                                <img src="{{ item.image.url }}"
                                                    class="img-fluid" alt="Изображение 1">
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <!-- Описание товара -->
                            <div class="card-body">
                                <div class="alert">
                                <h5 class="card-title">{{item.name}}</h5>
                                    <p class="card-text">{{item.description}}</p>
                                    <p class="card-text">Количество на складе: <strong>{{item.quantity}} литров </strong></p>
                                    <p class="card-text">Количество в <strong>701</strong> лаборатории: <strong> 5 литров </strong></p>
                                    <a href="#" class="btn btn-outline-dark">Количество необходимого реактива:</a>
                                    <input type="text" placeholder="Грамм">
                                <a href="{% url "experiment:experiment_add"%}" class="btn btn-dark add-to-experiment" data-item-id="{{item.id}}">

                                {% csrf_token %}
                                Добавить для экспериментов</a>
                                </div>

                            </div>
                        </div>
                    </div>
{% endblock %}